services:
  - type: web
    name: edtech-backend
    env: python
    plan: free
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.src.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    pullRequestPreviewsEnabled: true
