services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      - db
  agent:
    build:
      context: ..
      dockerfile: infra/Dockerfile.agent
    volumes:
      - ..:/workspace
    working_dir: /workspace

volumes:
  db_data:
